solution added
IrynaDim/Online-Shop pull request #1
Opened 2020-09-02 18:47 UTC by IrynaDim

2020-09-02 19:38 UTC, DmGrt reviewed
Great job! Just correct a little bit

2020-09-02 19:38 UTC, DmGrt commented on pom.xml
>  </project>
Add empty line

2020-09-02 19:38 UTC, DmGrt commented on src/main/java/com/internet/shop/dao/ProductDaoImpl.java
> +            if (Storage.products.get(i) == product) {
here better to use equals for Products

2020-09-03 06:45 UTC, IrynaDim commented on src/main/java/com/internet/shop/dao/ProductDaoImpl.java
> +            if (Storage.products.get(i) == product) {
точно)) то випадково щось затупила) чогось вирішила що то цифри)))))

2020-09-03 08:50 UTC, KseniiaMakarova requested changes

2020-09-03 08:50 UTC, KseniiaMakarova commented on pom.xml
> +        </dependency>
let's remove it - currently we don't use it

2020-09-03 08:50 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/dao/ProductDao.java
> +    List<Product> getAllProducts();
```suggestion
    boolean delete(Long productId);
    
    List<Product> getAll();
```

2020-09-03 08:50 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/dao/ProductDaoImpl.java
> +        return Optional.empty();
let's use findFirst()

2020-09-03 08:50 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/dao/ProductDaoImpl.java
> +package com.internet.shop.dao;
```suggestion
package com.internet.shop.dao.impl;
```

2020-09-03 08:50 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/dao/ProductDaoImpl.java
> +        }
the logic is ok, but let's use Stream API

2020-09-03 08:50 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/dao/ProductDaoImpl.java
> +        return true;
we can use `removeIf()` on storage

2020-09-03 08:50 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/db/Storage.java
> +        product.setId(productId++);
```suggestion
        product.setId(++productId);
```
ids should start with 1

2020-09-03 08:50 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/model/Order.java
> +        this.products = products;
id is set in storage
and we won't receive product list from outside

2020-09-03 08:50 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/model/Product.java
> +    private BigDecimal price;
let's make this field double for now

2020-09-03 08:50 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/model/ShoppingCart.java
> +        this.products = products;
id is set in storage
and we won't receive product list from outside

2020-09-03 08:50 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/model/User.java
> +        this.id = id;
id is set in storage

2020-09-03 08:50 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/service/ProductService.java
> +
```suggestion
    boolean delete(Long productId);

    List<Product> getAll();
```

2020-09-03 08:50 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/service/impl/ProductServiceImpl.java
> +        return productDao.getById(id).orElseThrow();
let's use `get()` for now

2020-09-03 08:50 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/Application.java
> +        Product product1 = new Product("Cup", new BigDecimal(80.0));
make your product names informative

2020-09-03 08:50 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/Application.java
> +        productService.get(4L);
```suggestion
        productService.get(someProduct,getId());
```
let's avoid hardcode

2020-09-03 09:49 UTC, IrynaDim commented on src/main/java/com/internet/shop/dao/ProductDao.java
> +    List<Product> getAllProducts();
+

2020-09-03 09:51 UTC, IrynaDim commented on src/main/java/com/internet/shop/dao/ProductDaoImpl.java
> +package com.internet.shop.dao;
+

2020-09-03 09:57 UTC, IrynaDim commented on src/main/java/com/internet/shop/service/ProductService.java
> +
done

2020-09-03 09:59 UTC, IrynaDim commented on src/main/java/com/internet/shop/service/impl/ProductServiceImpl.java
> +        return productDao.getById(id).orElseThrow();
done. if i understant correct))

2020-09-03 09:59 UTC, IrynaDim commented on src/main/java/com/internet/shop/Application.java
> +        Product product1 = new Product("Cup", new BigDecimal(80.0));
done

2020-09-03 10:44 UTC, KseniiaMakarova requested changes

2020-09-03 10:44 UTC, KseniiaMakarova commented on pom.xml
> +    </dependencies>
we can remove this

2020-09-03 10:44 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/dao/ProductDao.java
> +
```suggestion
```

2020-09-03 10:44 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/dao/impl/ProductDaoImpl.java
> +                .findFirst().orElseThrow());
```suggestion
        return Storage.products.stream()
                .filter(product -> product.getId() == productId)
                .findFirst();
```

also, do we use `==` to compare object types?

2020-09-03 10:44 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/dao/impl/ProductDaoImpl.java
> +        return Storage.products.removeIf(product -> (product.getId() == productId));
same question about `==`, check all your methods

2020-09-03 10:44 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/model/Order.java
> +        this.products = products;
we will not receive `products` from outside
remove this from method arguments and initialize as empty `ArrayList`

2020-09-03 10:44 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/model/ShoppingCart.java
> +        this.products = products;
same here

2020-09-03 10:44 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/service/ProductService.java
> +public interface ProductService {
`@Dao`?

2020-09-03 10:44 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/service/impl/ProductServiceImpl.java
> +        return productDao.get(id).orElseThrow();
```suggestion
        return productDao.get(id).get();
```

2020-09-03 10:44 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/service/impl/ProductServiceImpl.java
> +        return productDao.delete(productId);
```suggestion
        return productDao.delete(productId);
```

2020-09-03 12:41 UTC, KseniiaMakarova requested changes

2020-09-03 12:41 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/dao/impl/ProductDaoImpl.java
> +                .map(x -> product);
this doesn't cause changes in our storage
the elements are changed only in this stream

let's create IntStream of indices, than filter out only those indices on which there are elements with the same id
then for each of the remaining indices, **replace the element in storage** with our `product`

2020-09-04 06:24 UTC, KseniiaMakarova approved these changes

2020-09-04 09:25 UTC, merged